### ISSUE TITLE
Tester feiler ikke etter utsjekk

### ISSUE THREAD

**Issue by tmcheung** [arktekk/javazone-workshop-parser-combinators#14]
Ref Prerequisites i https://2024.javazone.no/program/5ad28847-cdc1-483a-b045-388e56895f88:

>  kjør testene (disse skal feile) med `sbt test`

Ikke noe big deal men det at testene ikke "feiler" kan være litt forvirrende for folk som har lite til ingen scala/sbt erfaring.
Kanskje litt sent å gjøre noe nå, men kan sikkert være greit å nevne under workshoppen.

**Comment by hamnis** [comment]
Det ble skrevet før vi fant ut av vi kunne gjøre testene pending i stedet. 

Jeg skal oppdatere teksten, selv om det er nå litt seint.

**Comment by hamnis** [comment]
Takk for beskjed forøvrig! @tmcheung

**Comment by hamnis** [comment]
teksten er oppdatert, så får vi se om den kommer gjennom cachen til javazone før i morgen.
